markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : calarts.github.io
production_url : http://calarts.github.io
description: "calarts code home."
#disqus_shortname: caarlos0blog
#analytics: UA-32899481-1
#gauges: 50f2b533613f5d7c8000000c
author :
  name : CalArts
  github : douglasgoodwin
  email: dgoodwin@calarts.edu
